### PR TITLE
[build]: fix dockerfile build args parsing

### LINKED ISSUE #1295: [Bug]: Default values for build args are ignored
### I have done the following

- [x] I have searched the existing issues
- [ ] If possible, I've reproduced the issue using the 'main' branch of this project

### Steps to reproduce

Dockerfile:

```dockerfile
ARG PYTHON_IMAGE="python:3.13-slim"
FROM ${PYTHON_IMAGE} AS builder
```

First build it without explicitly passing this value, then try building by explicitly passing it as a build arg.

Example using the `container` CLI:

```bash
container build

container build --build-arg PYTHON_IMAGE="python:3.13-slim"
```

### Current behavior

The first command fails because the default value is not used to fill in the arg when you don't supply it. The second command works as expected.

```sh
container build

[+] Building 0.0s (0/0)
Error: unknown (2): failed to solve: invalid ref: ${PYTHON_IMAGE}
```

Note that this _does_ work as expected when building with alternatives like Docker and Rancher (= Lima under the hood).

### Expected behavior

The first command also works, by using the supplied default value from the Dockerfile.

### Environment

```markdown
- OS: macOS 26.3.1
- Xcode: Version 26.3
- Container: container CLI version 0.10.0 (build: release, commit: 6bdb647)
```

### Relevant log output

```shell
N/A
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by saehejkang**
## Type of Change
- [x] Bug fix
- [ ] New feature  
- [ ] Breaking change
- [ ] Documentation update

## Motivation and Context
Closes https://github.com/apple/container/issues/1295

Normalize quoted build args so the `Dockerfile` sees the correct value passed through the build pipeline. When using the `--build-arg` flag, any quoted value is stripped by one layer, which is the correct behavior. 

However, passing a `Dockerfile` default like below was being literally read and caused reference issues. 

```dockerfile
# Passed value
ARG PYTHON_IMAGE="python:3.13-slim"
# Normalized
ARG PYTHON_IMAGE=python:3.13-slim
``` 

If the intent is to pass a quoted value, only one layer of quotes is stripped, so it is kept intact with proper quotes.

```dockerfile
# Passed value
ARG MYSTRING='"Hello, world!"'
# Normalized
ARG MYSTRING="Hello, world!"
```

## Testing
- [x] Tested locally
- [x] Added/updated tests
- [ ] Added/updated docs

### CODE REVIEW

**Comment by saehejkang** [comment]
> Could you describe more why it was the problem? just out of my curiosity :)

I started with some reverse engineering/research into `buildkit` itself. While doing so, I found this issue [here](https://github.com/moby/buildkit/issues/717) that seemed very similar 🤔 . Then, I walked through the `buildopts.go` file and saw how the args were read both ways: passed through the `Dockerfile` or passed to `--build-arg`. After a quick little comparison of what was being passed, I came to the conclusion, that `buildkit` stores the values from `ARG` literally. Having the extraneous quotes added would cause issues and below is an example of how that looks.

```dockerfile
ARG PYTHON_IMAGE="python:3.13-slim"
FROM ${PYTHON_IMAGE} AS builder
```

Would be read as 

```Dockerfile
FROM "python:3.13-slim" AS builder
```

Hope that makes some sense 😅.

File: pkg/build/buildopts.go [hunk 1]
```diff
@@ -138,6 +138,11 @@ func NewBuildOpts(ctx context.Context, basePath string, contextMap map[string][]
 		bps = append(bps, platforms.DefaultSpec())
 	}
 
+	normalizeBuildArg := func(arg string) string {
+		arg = strings.TrimSpace(arg)
+		return strings.Trim(arg, `"'`)
```
Comment (jglogan) [inline pkg/build/buildopts.go]: @saehejkang  Hi! What do we think this should evaluate to?

```Dockerfile
ARG MYSTRING='"Hello, world!"'
```

Comment (saehejkang) [reply pkg/build/buildopts.go]: > Hi! What do we think this should evaluate to?

```Dockerfile
ARG MYSTRING="Hello, world!"
```

That is an edge case I did not account for. I am new to the builder and how things work, so I can continue digging into this. Am I at least on the right track with how to fix the issue at hand 🤔 ?

Comment (JaewonHur) [reply pkg/build/buildopts.go]: I believe so :)

**Comment by JaewonHur** [comment]
Hi @saehejkang 
I made some test cases for these!

Attached archive has 4 Dockerfiles: `Dockerfile.base`, `Dockerfile.quoted`, `Dockerfile.variableInDoubleQuote`, and `Dockerfile.variableInSingleQuote`.
You can run `container build -f <dockerfile-path> .`.

Docker passes all except `Dockerfile.variableInSingleQuote`.
This PR fails `Dockerfile.variableInDoubleQuote` also.
Could you check?

[dockerfiles.zip](https://github.com/user-attachments/files/26219955/dockerfiles.zip)

**Comment by JaewonHur** [comment]
Additionally I asked Claude to check how buildkit correctly parses build args.
Here's what it said. Hope this would be helpful to you.

```

  ---
  How shlex unquotes build arg values

  The key insight is that shlex.ProcessWordWithMatches does two things simultaneously: variable substitution AND
  shell-style quote removal.

  The call chain

  buildMetaArgs (convert.go:2662)
    → shlex.ProcessWordWithMatches(*kp.Value, args)
      → s.process(word, env, true)
        → sw.processStopOn(scanner.EOF, ...)

  Quote removal in processStopOn (lex.go:169)

  The scanner walks the value character by character. When SkipProcessQuotes is false (the default), it registers
  special handlers:

  charFuncMapping['\''] = sw.processSingleQuote
  charFuncMapping['"']  = sw.processDoubleQuote

  When a ' or " is encountered, the corresponding function is called instead of emitting the character:

  - processSingleQuote (lex.go:246): consumes the opening ', reads everything until the closing ' literally, and
  returns the content without the surrounding quotes.
  - processDoubleQuote (lex.go:278): does the same for ", but also processes $ inside (for variable substitution).

  So if a Dockerfile has:
  ARG VERSION="1.0"
  The value stored is "1.0". When ProcessWordWithMatches runs on it, processDoubleQuote fires, consumes both "
  characters, and result.String() ends up as 1.0 — the quotes are gone.

  Variable substitution enabling forward references

  The args parameter passed to ProcessWordWithMatches is an *llb.EnvList that is accumulated incrementally inside
  the buildMetaArgs loop:

  // convert.go:2685
  args = args.AddOrReplace(kp.Key, *kp.Value)

  Each ARG's resolved value is added to args before processing the next one. So when the shlex processes $PREV_ARG
  inside a later ARG's value, it finds it in the env map — this is what the PR fixed: before, the shlex step was
  missing so neither substitution nor unquoting happened.

  Summary

  ┌───────────────┬──────────────────────────────────────────────────────┐
  │  Input value  │             After ProcessWordWithMatches             │
  ├───────────────┼──────────────────────────────────────────────────────┤
  │ "hello"       │ hello (quotes stripped by processDoubleQuote)        │
  ├───────────────┼──────────────────────────────────────────────────────┤
  │ 'hello'       │ hello (quotes stripped by processSingleQuote)        │
  ├───────────────┼──────────────────────────────────────────────────────┤
  │ $BASE-suffix  │ <BASE value>-suffix (substitution via processDollar) │
  ├───────────────┼──────────────────────────────────────────────────────┤
  │ "${BASE}-img" │ <BASE value>-img (both at once)                      │
  └───────────────┴──────────────────────────────────────────────────────┘
```

**Comment by saehejkang** [comment]
> Docker passes all except Dockerfile.variableInSingleQuote

It does not seem to be standard behavior, like you mentioned, so I assume we want to ignore that case?

> Hope this would be helpful to you.

Very helpful and was honestly the last missing piece to the puzzle. I tend to try and figure out as much as I can with little AI and then use it if I ever get a little stuck 😅 .

> Could you check?

All files except `Dockerfile.variableInSingleQuote` (as expected) passed. [PR](https://github.com/apple/container/pull/1342) adding tests to `container`, once everything here looks good.

File: pkg/build/buildopts.go [hunk 2]
```diff
@@ -251,9 +262,16 @@ func NewBuildOpts(ctx context.Context, basePath string, contextMap map[string][]
...
+			if _, ok := buildArgs[arg.Key]; ok {
+				continue
+			}
+			// Expand with prior args and strip shell quotes
+			resolved, err := shell.NewLex('\\').ProcessWordWithMatches(arg.ValueString(), utils.NewMapGetter(buildArgs))
+			if err != nil {
+				return nil, err
 			}
+			// Save the resolved value for later use
+			buildArgs[arg.Key] = normalizeBuildArg(resolved.Result)
```
Comment (JaewonHur) [inline pkg/build/buildopts.go]: I guess it's minor, but we might just do `buildArgs[arg.Key] = resolved.Result` 😅 

Following Dockerfile fails in docker, but succeeds here.

```
ARG DEBIAN="'debian'"

FROM "${DEBIAN}:bookworm"

CMD ["echo", "hello"]
```

`ProcessWordWithMatches` already strips outermost quotes `"`.

Comment (saehejkang) [reply pkg/build/buildopts.go]: Hmmm. I tested it both ways and looks like the normalization function is needed. Are you getting a different outcome on your end?

`no normalizeBuildArg`

```bash
[+] Building 0.0s (0/0)                                                                                                                                                                                            
Error: unknown (2): failed to solve: invalid ref: "${DEBIAN}:bookworm"
```

`normalizeBuildArg`

```bash
[+] Building 2.6s (5/5) FINISHED                                                                                                                                                                                   
 => [resolver] fetching image...docker.io/library/debian:bookworm  
```

Comment (JaewonHur) [reply pkg/build/buildopts.go]: I mean it should fail as Docker build also fails.

Comment (JaewonHur) [reply pkg/build/buildopts.go]: `ARG DEBIAN="'debian'"` should be resolved to `'debian'`, but with `normalizeBuildArg`, it is resolved to `debian`.

Comment (saehejkang) [reply pkg/build/buildopts.go]: Below is a table of all the types of files, with the expected outcome for both `Docker` and `Container`. Let me know if this looks good to you!

| Name | Dockerfile | Docker Pass? | Container Should Pass? |
|------|------------|--------------|------------------------|
| base | `ARG DEBIAN=debian:bookworm; FROM $DEBIAN` | ✅ | ✅ |
| variableInSingleQuote | `ARG DEBIAN="debian"; ARG IMAGE='${DEBIAN}:bookworm'; FROM $IMAGE` | ❌ | ❌ |
| quoted | `ARG DEBIAN="debian:bookworm"; FROM $DEBIAN` | ✅ | ✅ |
| variableInDoubleQuote | `ARG DEBIAN="debian"; ARG IMAGE="${DEBIAN}:bookworm"; FROM $IMAGE` | ✅ | ✅ |
| variableInDoubleDoubleQuote | `ARG DEBIAN="'debian'"; FROM "${DEBIAN}:bookworm"` | ❌ | ❌ |

Comment (JaewonHur) [reply pkg/build/buildopts.go]: On my Mac, container passes that last test `variableInDoubleDoubleQuote`. Could you check one last time?

Comment (saehejkang) [reply pkg/build/buildopts.go]: Yes, I did not push the changes yet and just wanted to verify proper functionality with the table above. The changes have been pushed and `variableInDoubleDoubleQuote` should now fail (as expected).

Comment (JaewonHur) [reply pkg/build/buildopts.go]: Cool! Thanks!

**Review by JaewonHur — APPROVED** [review]
