### PR TITLE
[frontend]: resolve copy --from image references

### LINKED ISSUE #1240: [Bug]: container build fails to resolve local images in COPY --from
### I have done the following

- [x] I have searched the existing issues
- [x] If possible, I've reproduced the issue using the 'main' branch of this project

### Steps to reproduce

```bash
cat >Dockerfile.base <<'EOF'
FROM alpine:latest
RUN echo hello >/hello.txt
EOF

cat >Dockerfile.test <<'EOF'
FROM alpine:latest
COPY --from=bug-base /hello.txt /copied.txt
RUN cat /copied.txt
EOF

container build -t bug-base -f Dockerfile.base .
container build -t bug-test -f Dockerfile.test .
```

### Current behavior

It tries to pull a non-existent image from docker.io rather then using a local image.

### Expected behavior

`COPY --from=<tag>` should use a local image with that tag first if available, just like `FROM <tag>` does.

### Environment

```markdown
- OS: macOS 26.2
- Xcode: i don't use it
- Container: container CLI version 0.9.0 (build: release, commit: 3e49dce)
```

### Relevant log output

```shell
+ container build -t bug-base -f Dockerfile.base .
[+] Building 4.0s (5/5) FINISHED
 => [resolver] fetching image...docker.io/library/alpine:latest                                                                                          0.0s
 => [internal] load .dockerignore                                                                                                                        0.0s
 => => transferring context: 2B                                                                                                                          0.0s
 => oci-layout://docker.io/library/alpine:latest@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659                                 0.0s
 => => resolve docker.io/library/alpine:latest@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659                                   0.0s
 => CACHED [linux/arm64 1/2] RUN echo hello >/hello.txt                                                                                                  0.0s
 => exporting to oci image format                                                                                                                        0.0s
 => => exporting layers                                                                                                                                  0.0s
 => => exporting manifest sha256:fad670ed74832a71f87d6cdf26a2083bce90651dddee35c328790f43532cb8da                                                        0.0s
 => => exporting config sha256:b8376d1efdb7f2b30e0bdc3f227b751fab323fcf0c81628505262d580d24a6f0                                                          0.0s
 => => exporting manifest list sha256:9891ae92d2f8a70aedcf316a926307c075ce319f4411c6f5eaedf5a885703271                                                   0.0s
 => => sending tarball                                                                                                                                   0.0s
Successfully built bug-base:latest
+ container build -t bug-test -f Dockerfile.test .
[+] Building 0.0s (0/1)
 => [resolver] fetching image...docker.io/library/alpine:latest                                                                                          0.0s
Error: internalError: "HTTP request to https://registry-1.docker.io/v2/library/bug-base/manifests/latest failed with response: 401 Unauthorized. Reason: Unknown, no credentials found for host registry-1.docker.io"
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by saehejkang**
Closes https://github.com/apple/container/issues/1240

Resolve COPY --from image references so `BuildKit` uses the local/named context path instead of falling back to pull the image from the remote repository.

### CODE REVIEW

File: pkg/build/frontend.go [hunk 1]
```diff
@@ -168,86 +237,24 @@ func resolveStates(ctx context.Context, bopts *BOpts, platform ocispecs.Platform
...
 	}
 	go func() { wg.Wait(); doneCh <- struct{}{} }()
 	select {
 	case err := <-errCh:
 		return nil, err
 	case <-doneCh:
 	}
+
+	if err := preseedCopyFromSources(stages, platform, resolveSource); err != nil {
+		errCh <- err
```
Comment (JaewonHur) [inline pkg/build/frontend.go]: This will block forever as no one is listening on `errCh`.
We should just `return nil, err`.

File: pkg/build/frontend.go [hunk 2]
```diff
@@ -424,6 +431,35 @@ func solvePlatform(ctx context.Context, bopts *BOpts, pl ocispecs.Platform, c ga
...
+			if !ok || c.From == "" {
+				continue
+			}
+			// Skip numeric stage indexes.
+			_, err := strconv.Atoi(c.From)
+			if err == nil {
+				continue
+			}
+			namedIndex, hasNamedStage := instructions.HasStage(stages, c.From)
+			if hasNamedStage && namedIndex < i {
```
Comment (JaewonHur) [inline pkg/build/frontend.go]: `COPY --from` can reference the stage defined after this stage (i.e., buildkit will build dependency graph based on it). 
Thus this should be just `if hasNamedStage { continue }`.

**Comment by JaewonHur** [comment]
@saehejkang Hi! Thank you for looking into this issue!

I left some comments there. In apple/container#1380, could you please add more test cases including failing tests?

**Comment by saehejkang** [comment]
> I left some comments there. In https://github.com/apple/container/pull/1380, could you please add more test cases including failing tests?

Done!

**Comment by JaewonHur** [comment]
Cool! Thanks!

**Review by JaewonHur — APPROVED** [review]
